mvc/mvc/Models/CountAliceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mvc.Models
{
    public class CountAliceViewModel
    {
        public string text { get; set; }
        public int count {get; set;}
    }

}

mvc/mvc/Models/FactorialViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mvc.Models
{
    public class FactorialViewModel
    {
        public int[] number { get; set; }
        public int factorial { get; set; }
    }

    public class FactorialPostModel
    {
        public int[] number { get; set; }
    }
}

mvc/mvc/Models/MaxViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mvc.Models
{
    public class MaxViewModel
    {
        public int[] numbers { get; set; }
        public int max { get; set; }
    }

    public class MaxPostModel
    {
        public int number1 { get; set; }
        public int number2 { get; set; }
        public int number3 { get; set; }
    }
}

mvc/mvc/Models/MultiplyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mvc.Models
{
    public class MultiplyViewModel
    {
        public int[] numbers { get; set; }
        public int multiply { get; set; }
    }

    public class MultiplyPostModel
    {
        public int number1 { get; set; }
        public int number2 { get; set; }
        public int number3 { get; set; }
    }
}

mvc/mvc/Models/PalindromeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mvc.Models
{
    public class PalindromeViewModel
    {
        public string text { get; set; }
        public bool palindrome { get; set; }
    }
}

mvc/mvc/Models/SumViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mvc.Models
{
    public class SumViewModel
    {
        public int number1 { get; set; }
        public int number2 { get; set; }
        public int sum { get; set; }

        public void SetSum()
        {
            sum = number1 + number2;
        }
    }
    
    public class SumPostModel
    {
        public int number1 { get; set; }
        public int number2 { get; set; }
    }
}

mvc/mvc/Models/WordFrequencyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace mvc.Models
{
    public class WordFrequencyViewModel
    {
        public string text { get; set; }
        public Dictionary<string, int> frequencies { get; set; }
    }
}

mvc/mvc/Controllers/ExercisesController.cs
using mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class ExercisesController : Controller
    {
        [HttpGet]
        public ActionResult Sum()
        {
            return View();
        }

        [HttpPost]
        public ActionResult sum(string input)
        {
            List<int> numbers = new List<int>();

            foreach (var number in input.Split(','))
            {
                int t;
                if (Int32.TryParse(number, out t))
                {
                    numbers.Add(t);
                }
            }
            var thingy = new Mathinator(numbers.ToArray());

            var responseModel = new SumViewModel
            {
                numbers = thingy.numbers,
                sum = thingy.sum()
            }; 
            return View(responseModel);
        }


        [HttpGet]
        public ActionResult Multiply(MultiplyPostModel model)
        {
            return View();

        }

        [HttpPost]
        public ActionResult Multiply(string input)
        {

            List<int> numbers = new List<int>();

            foreach(var number in input.Split(',') )
            {
                int t;
                if (Int32.TryParse(number, out t))
                {
                    numbers.Add(t);
                }
            }


            var times = new Mathinator(numbers.ToArray());

            var responseModel = new MultiplyViewModel
            {
                numbers = times.numbers,
                multiply = times.multiply()
            };
            return View(responseModel);
        }
        [HttpGet]
        public ActionResult FindLongestWord()
        {
            return View();
        }
        [HttpPost]
        public ActionResult FindLongestWord(string text)
        {
            var wordinator = new Wordinator(text);
            var responseModel = new LongestWordViewModel
           {
               text = text,
               longest = wordinator.findLongestWord()

           };
            return View(responseModel);
        }
        [HttpGet]
        public ActionResult CountAlice()
        {
            return View();
        
        }
        [HttpPost]
        public ActionResult CountAlice(string text)
        {

            var wordinator = new Wordinator(text);

            var responseModel = new CountAliceViewModel
            {
                text = text,
                count = wordinator.countAlice()
            };
            
            return View(responseModel);
        }

        [HttpGet]
        public ActionResult Max()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Max(MaxPostModel model)
        {
            var math = new Mathinator(new[] { model.number1, model.number2, model.number3 });
            var responseModel = new MaxViewModel
            {
                numbers = math.numbers,
                max = math.Max()
            };

            return View(responseModel);
        }

        [HttpGet]
        public ActionResult wordFrequency()
        {
            return View();
        }

        [HttpPost]
        public ActionResult wordFrequency(string text)
        {
            var wordinator = new Wordinator(text);
            var responseModel = new WordFrequencyViewModel();
            responseModel.text = text;
            responseModel.frequencies = wordinator.WordFrequency();

            return View(responseModel);
        }

        [HttpGet]
        public ActionResult factorial()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult factorial(int num)
            {
                var responseModel = new FactorialViewModel
            {
                number = num,
                factorial = Mathinator.factorial(num)

            };
            return View(responseModel);
        }

        [HttpGet]
        public ActionResult palindrome()
        {
            return View();

        }
        [HttpPost]
        public ActionResult palindrome(string text)
        {

            var pal = new Wordinator(text);

            var responseModel = new PalindromeViewModel
            {
                text = text,
                palindrome = pal.palindrome(text)
            };

            return View(responseModel);
        }
        [HttpGet]
        public ActionResult printNumbers()
        {
            return View();
        }

        [HttpPost]
        public ActionResult printNumbers(int num1, int num2)
        {
           var responseModel = new NumbersViewModel();
           responseModel.num1 = num1;
           responseModel.num2 = num2;
           responseModel.output = Mathinator.printNumbers(num1, num2);

      
           return View(responseModel);
        }

        [HttpGet]
        public ActionResult perfectNumber()
        {
            return View();
        }

        /*[HttpPost]
        public ActionResult perfectNumber(int num1)
        {
            var responseModel = new PerfectViewModel();
            responseModel.num1 = num1;
            responseModel.result = Mathinator.perfectNumber(num1);

            return View(responseModel);
        }*/

        [HttpGet]
        public ActionResult filterLongstWord()
        {
            return View();
        }

        /*[HttpPost]
        public ActionResult filterLongestWord(string text, int i)
        {
            var wordinator = new Wordinator(text);
            var responseModel = new FilterViewModel();
            responseModel.i = i;
            responseModel.text = wordinator.filterLongestWord(i);

            return View(responseModel);
        }*/

        }
 }  


    
 
 

mvc/mvc/Views/Exercises/CountAlice.cshtml
@model mvc.Models.CountAliceViewModel

@{
    ViewBag.Title = "CountAlice";
}

<h2>CountAlice</h2>


<h5>How many times does Alice appear</h5>

<div class="row">
    <form action="@Url.Action("CountAlice", "Exercises")" method="post">
        <textarea name="text" class=""
                  style="height:300px; width: 100%;">
            @if (Model != null)
            {
                @Model.text
            }
        </textarea>
        <br />
        <button type="submit">Count</button><br />
        <label>Alice appears this many times: </label><input type="number" value="@if(Model!=null){@Model.count}" disabled /> <br />
    </form>
</div>

mvc/mvc/Views/Exercises/Factorial.cshtml
@model mvc.Models.FactorialViewModel

@{
    ViewBag.Title = "Factorial";
}

<h2>Factorial</h2>

<form action="@Url.Action("Factorial", "Exercises")" method="post">
    <label>Input Number</label><input type="number" name="num" value="@if(Model != null){ @Model.number}" /> <br />
    <label>Factorial: </label><input type="number" name="factorial" value="@if(Model != null){ @Model.factorial}" disabled /> <br />
    <button type="submit">Get Factorial</button>
</form>

mvc/mvc/Views/Exercises/FindLongestWord.cshtml
@model mvc.Models.LongestWordViewModel

@{
    ViewBag.Title = "FindLongestWord";
}

<h2>FindLongestWord</h2>


<h5> Longest Word </h5>


<div class="row">
    <form action="@Url.Action("FindLongestWord", "Exercises")" method="post">
        <textarea name="text" class=""
                  style="height:300px; width: 100%;">
            @if (Model != null)
            {
                @Model.text
            }
        </textarea>
        <br />
        <button type="submit">Find Largest Word</button><br />
        <label>The Longest Word Is: </label><input type="text" value="@if(Model!=null){@Model.longest}" disabled /> <br />
    </form>
</div>

mvc/mvc/Views/Exercises/Max.cshtml
@model mvc.Models.MaxViewModel

@{
    ViewBag.Title = "Max";
}

<h2>Max</h2>

<form action="@Url.Action("Max", "Exercises")" method="post">
    <label>Input Number</label><input type="number" name="number1" value="@if(Model != null){ @Model.numbers[0]}" /> <br />
    <label>Input Number</label><input type="number" name="number2" value="@if(Model != null){ @Model.numbers[1]}" /> <br />
    <label>Input Number</label><input type="number" name="number3" value="@if(Model != null){ @Model.numbers[2]}" /> <br />
    <label>Highest Number: </label><input type="number" name="sum" value="@if(Model != null){ @Model.max}" disabled /> <br />
    <button type="submit">Get Max</button>
</form>

mvc/mvc/Views/Exercises/Multiply.cshtml
@model mvc.Models.MultiplyViewModel

@{
    ViewBag.Title = "Multiply";
    string numbers = "";
    if(Model != null)
    {
        foreach (var number in Model.numbers)
        {
            numbers += number.ToString() + ", ";
        }
    }
}

<h2>Multiply</h2>

<form action="@Url.Action("Multiply", "Exercises")" method="post">
    <label>Input Number</label><input type="text" name="input" value="@if(Model != null){ @numbers }" /> <br />
    <label>Multiplication Value: </label><input type="number" name="multiply" value="@if(Model != null){ @Model.multiply}" disabled /> <br />
    <button type="submit">Get Multiplication Value</button>
</form>

mvc/mvc/Views/Exercises/Palindrome.cshtml
@model mvc.Models.PalindromeViewModel

@{
    ViewBag.Title = "Palindrome";
}

<h2>Palindrome</h2>

<form action="@Url.Action("Palindrome", "Exercises")" method="post">
    <label>Word</label><input type="text" name="text" value="@if(Model != null){ @Model.text }" /> <br />
    <label>Palindrome: </label><input type="text" name="palindrome" value="@if(Model != null){ @Model.palindrome}" disabled /> <br />
    <button type="submit">Check to see if word is a palindrome</button>
</form>

mvc/mvc/Views/Exercises/PerfectNumbers.cshtml
@model mvc.Models.PerfectViewModel

@{
    ViewBag.Title = "PerfectNumbers";
}

<h2>PerfectNumbers</h2>

<form action="@Url.Action("PerfectNumbers", "Exercises")" method="post">
    <label>Input Number</label><input type="number" name="num1" value="@if(Model != null){ @Model.num1}" /> <br />
    <label>Sum: </label><input type="text" name="result" value="@if(Model != null){ @Model.result}" disabled /> <br />
    <button type="submit">Check to see if it is a perfect number</button>
</form>

mvc/mvc/Views/Exercises/PrintNumbers.cshtml
@model mvc.Models.NumbersViewModel

@{
    ViewBag.Title = "PrintNumbers";
}

@if (Model != null)
{
    Html.Raw(Model.output);
}


<h2>PrintNumbers</h2>

<form action="@Url.Action("PrintNumbers", "Exercises")" method="post">
    <label>Input Number1</label><input type="number" name="num1" value="@if(Model != null){ @Model.num1 }" /> <br />
    <label>Input Number2</label><input type="number" name="num2" value="@if(Model != null){ @Model.num2 }" /> <br />

    <button type="submit">Print Numbers</button>
</form>

@if(Model != null)
{
    @Html.Raw(Model.output);
}

mvc/mvc/Views/Exercises/Sum.cshtml
@model mvc.Models.SumViewModel

@{
    ViewBag.Title = "Sum";
    string numbers = "";
    if (Model != null)
    {
        foreach (var number in Model.numbers)
        {
            numbers += number.ToString() + ", ";
        }
    }
}

<h2>Sum</h2>


<form action="@Url.Action("Sum", "Exercises")" method="post">
    <label>Input Number</label><input type="text" name="input" value="@if(Model != null){ @numbers }" /> <br />
    <label>Sum: </label><input type="number" name="sum" value="@if(Model != null){ @Model.sum}" disabled /> <br/>
    <button type="submit">Get Sum</button>
</form>

mvc/mvc/Views/Exercises/WordFrequency.cshtml
@model mvc.Models.WordFrequencyViewModel

@{
    ViewBag.Title = "WordFrequency";
}

<h2>WordFrequency</h2>

<div class="row">
    <form action="@Url.Action("WordFrequency", "Exercises")" method="post">
        <textarea name="text" class=""
                  style="height:300px; width: 100%;">
            @if (Model != null)
            {
                @Model.text
            }
        </textarea>
        <br />
        <button type="submit">Count</button><br />
        @if(Model!=null){@Model.frequencies} <br />
    </form>
</div>